
version: '3'

services:
  web:
    build: .
    volumes:
      - .:/app
    command: sh -c "pip install --upgrade pip && pip install -r requirements.txt && python3 manage.py runserver 0.0.0.0:8085"
    ports:
      - "8000:8085"
    env_file:
      - .env
    working_dir: /app 

volumes:
  postgres_data:
        
        