# Generated by Django 4.1.1 on 2024-02-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Paciente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("sexo", models.CharField(max_length=100)),
                ("doença", models.CharField(max_length=100)),
                ("idade", models.IntegerField()),
                ("naturalidade", models.CharField(max_length=100)),
                ("onde_mora", models.CharField(max_length=100)),
                ("profissao", models.CharField(max_length=100)),
            ],
        ),
    ]
