# Generated by Django 4.1.1 on 2024-02-24 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="paciente",
            old_name="doença",
            new_name="doenca",
        ),
    ]
