# Generated by Django 4.1.1 on 2024-02-24 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_rename_doença_paciente_doenca"),
    ]

    operations = [
        migrations.CreateModel(
            name="Doenca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("sintomas", models.TextField()),
                ("descricao", models.TextField()),
            ],
        ),
    ]
