# Generated by Django 4.2.5 on 2024-03-30 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0003_doenca"),
    ]

    operations = [
        migrations.CreateModel(
            name="Aventura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("json", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="Historia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("texto", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Personagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("ficha", models.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name="Doenca",
        ),
        migrations.DeleteModel(
            name="Paciente",
        ),
    ]
