# Generated by Django 4.2.5 on 2024-03-30 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0004_aventura_historia_personagem_delete_doenca_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="personagem",
            name="caminho_img",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
